In [19]:
import os 
from pathlib import Path
import pandas as pd
import numpy as np
from tqdm import tqdm
from IPython.core.interactiveshell import InteractiveShell  
from ipywidgets import interact  
InteractiveShell.ast_node_interactivity = "all"   # type: ignore

In [20]:
a = 2
b = 3

a
b

2

3

In [ ]:

outputs_dir = Path().resolve().parent / "outputs"

print(outputs_dir.exists())
for experim_path in sorted(outputs_dir.iterdir()):
    all_train_metrics = sorted(experim_path.rglob("train/metrics.csv", case_sensitive=False))
    num_metrics = len(all_train_metrics)

    # Sizes are unknown unless peeking is performed
    sum = None
    sum_sq = None
    # Save initial path
    enum_metrics = enumerate(all_train_metrics)
    train_metric_path = next(enum_metrics)[1]
    df = pd.read_csv(train_metric_path.resolve())
    len(df)
    for i, train_metrics_path in enum_metrics:
        df = pd.read_csv(train_metrics_path.resolve())
        metrics = np.asarray(df.values)
        if i == 0:
            sum = np.zeros_like(metrics)
            sum_sq = np.zeros_like(metrics)

        assert sum_sq is not None and sum is not None, "Sum variables cannot be None permanently"
        sum = np.sum((sum, metrics), axis=[0])
        sum_sq = np.sum((sum_sq, np.square(metrics)), axis=0)

    assert sum_sq is not None and sum is not None, "Sum variables cannot be None permanently"
    total_mean = sum / num_metrics
    total_std = sum_sq / num_metrics

True

      step  train/acc  train/loss
0        0   0.140625    2.449495
1        1   0.132812    5.565987
2        2   0.151042    7.224979
3        3   0.140625    7.720687
4        4   0.134375    7.717870
...    ...        ...         ...
1995    95   0.902907    0.310369
1996    96   0.902956    0.310214
1997    97   0.902989    0.310086
1998    98   0.903030    0.309951
1999    99   0.903063    0.309825

[2000 rows x 3 columns]

      step  train/acc  train/loss
0        0   0.468750    5.555393
1        1   0.523438    4.481192
2        2   0.557292    3.976566
3        3   0.589844    3.556442
4        4   0.612500    3.084499
...    ...        ...         ...
1995    95   0.975208    0.078043
1996    96   0.975221    0.078008
1997    97   0.975233    0.077975
1998    98   0.975245    0.077936
1999    99   0.975258    0.077901

[2000 rows x 3 columns]

      step  train/acc  train/loss
0        0   0.562500    5.512945
1        1   0.695312    3.491324
2        2   0.739583    2.874664
3        3   0.722656    3.073832
4        4   0.737500    2.819068
...    ...        ...         ...
1995    95   0.979334    0.067035
1996    96   0.979336    0.067010
1997    97   0.979339    0.067088
1998    98   0.979349    0.067056
1999    99   0.979359    0.067024

[2000 rows x 3 columns]

      step  train/acc  train/loss
0        0   0.609375    5.517775
1        1   0.742188    3.144863
2        2   0.781250    2.409527
3        3   0.796875    2.114816
4        4   0.800000    2.024359
...    ...        ...         ...
1995    95   0.989095    0.037215
1996    96   0.989101    0.037196
1997    97   0.989106    0.037178
1998    98   0.989112    0.037159
1999    99   0.989117    0.037141

[2000 rows x 3 columns]

      step  train/acc  train/loss
0        0   0.640625    5.779038
1        1   0.742188    3.483973
2        2   0.776042    2.768107
3        3   0.789062    2.420346
4        4   0.818750    2.401273
...    ...        ...         ...
1995    95   0.989142    0.041775
1996    96   0.989148    0.041755
1997    97   0.989153    0.041734
1998    98   0.989159    0.041713
1999    99   0.989164    0.041692

[2000 rows x 3 columns]

      step  train/acc  train/loss
0        0   0.656250    4.423919
1        1   0.734375    2.940065
2        2   0.791667    2.070940
3        3   0.796875    1.779034
4        4   0.809375    1.656170
...    ...        ...         ...
1995    95   0.991475    0.030349
1996    96   0.991479    0.030336
1997    97   0.991484    0.030321
1998    98   0.991488    0.030306
1999    99   0.991492    0.030291

[2000 rows x 3 columns]

      step  train/acc  train/loss
0        0   0.484375    8.196728
1        1   0.640625    4.570733
2        2   0.697917    3.481266
3        3   0.738281    2.850503
4        4   0.775000    2.494165
...    ...        ...         ...
1995    95   0.990958    0.034451
1996    96   0.990955    0.034457
1997    97   0.990960    0.034440
1998    98   0.990964    0.034422
1999    99   0.990969    0.034405

[2000 rows x 3 columns]

     step  train/acc  train/loss
0       0   0.656250    3.466889
1       1   0.757812    2.069504
2       2   0.822917    1.460223
3       3   0.847656    1.165516
4       4   0.865625    1.038067
..    ...        ...         ...
895    95   0.989938    0.036802
896    96   0.989949    0.036771
897    97   0.989960    0.036731
898    98   0.989972    0.036690
899    99   0.989983    0.036649

[900 rows x 3 columns]

      step  train/acc  train/loss
0        0   0.140625    2.449495
1        1   0.242188    2.053354
2        2   0.265625    2.134542
3        3   0.277344    2.277567
4        4   0.303125    2.187751
...    ...        ...         ...
1995    95   0.984328    0.047469
1996    96   0.984336    0.047448
1997    97   0.984344    0.047424
1998    98   0.984352    0.047400
1999    99   0.984359    0.047377

[2000 rows x 3 columns]

      step  train/acc  train/loss
0        0   0.593750    5.746343
1        1   0.726562    3.591744
2        2   0.776042    2.681486
3        3   0.781250    2.430994
4        4   0.796875    2.126194
...    ...        ...         ...
1295    95   0.992646    0.030689
1296    96   0.992651    0.030667
1297    97   0.992657    0.030644
1298    98   0.992663    0.030623
1299    99   0.992668    0.030599

[1300 rows x 3 columns]