In [19]:
import os 
from pathlib import Path
import pandas as pd
import numpy as np
from tqdm import tqdm
from IPython.core.interactiveshell import InteractiveShell  
from ipywidgets import interact  
InteractiveShell.ast_node_interactivity = "all"   # type: ignore

In [20]:
a = 2
b = 3

a
b

2

3

In [39]:
outputs_dir = Path().resolve().parent / "outputs"

print(outputs_dir.exists())
for experim_path in sorted(outputs_dir.iterdir()):
    all_train_metrics = sorted(experim_path.rglob("train/metrics.csv", case_sensitive=False))
    num_metrics = len(all_train_metrics)

    # Sizes are unknown unless peeking is performed
    sum = np.zeros(0)
    sum_sq = np.zeros(0)
    max = np.zeros(0)
    min = np.zeros(0)
    header = [""]
    # Save initial path
    enumerated_metrics = enumerate(all_train_metrics)

    for i, train_metrics_path in enumerated_metrics:
        df = pd.read_csv(train_metrics_path.resolve())
        metrics = np.asarray(df.values)
        if i == 0:
            sum = np.zeros_like(metrics)
            sum_sq = np.zeros_like(metrics)
            header = df.columns

        sum = np.sum([sum, metrics], axis=(0))
        sum_sq = np.sum([sum_sq, np.square(metrics)], axis=(0))

    total_mean = sum / num_metrics
    total_std = sum_sq / num_metrics
    header = list(map(lambda title: f"mean_{title}", header))
    total_mean_df = pd.DataFrame(total_mean, columns=header)
    header = list(map(lambda title: f"std_{title}", header))
    total_std_df = pd.DataFrame(total_std, columns=header)
    total_mean_df 
    total_std_df

True

      mean_step  mean_train/acc  mean_train/loss
0           0.0        0.508929         5.347899
1           1.0        0.601562         3.954019
2           2.0        0.642113         3.543721
3           3.0        0.653460         3.359380
4           4.0        0.669643         3.171058
...         ...             ...              ...
1995       95.0        0.974017         0.085605
1996       96.0        0.974028         0.085568
1997       97.0        0.974038         0.085546
1998       98.0        0.974050         0.085506
1999       99.0        0.974060         0.085469

[2000 rows x 3 columns]

      std_mean_step  std_mean_train/acc  std_mean_train/loss
0               0.0            0.286133            31.122216
1               1.0            0.403782            16.402063
2               4.0            0.458112            15.164763
3               9.0            0.475374            14.760942
4              16.0            0.500455            13.693528
...             ...                 ...                  ...
1995         9025.0            0.949586             0.016022
1996         9216.0            0.949606             0.016006
1997         9409.0            0.949624             0.015995
1998         9604.0            0.949647             0.015981
1999         9801.0            0.949667             0.015967

[2000 rows x 3 columns]

      mean_step  mean_train/acc  mean_train/loss
0           0.0        0.140625         2.449495
1           1.0        0.242188         2.053354
2           2.0        0.265625         2.134542
3           3.0        0.277344         2.277567
4           4.0        0.303125         2.187751
...         ...             ...              ...
1995       95.0        0.984328         0.047469
1996       96.0        0.984336         0.047448
1997       97.0        0.984344         0.047424
1998       98.0        0.984352         0.047400
1999       99.0        0.984359         0.047377

[2000 rows x 3 columns]

      std_mean_step  std_mean_train/acc  std_mean_train/loss
0               0.0            0.019775             6.000027
1               1.0            0.058655             4.216263
2               4.0            0.070557             4.556268
3               9.0            0.076920             5.187313
4              16.0            0.091885             4.786255
...             ...                 ...                  ...
1995         9025.0            0.968902             0.002253
1996         9216.0            0.968917             0.002251
1997         9409.0            0.968933             0.002249
1998         9604.0            0.968948             0.002247
1999         9801.0            0.968963             0.002245

[2000 rows x 3 columns]